networks:
  dnsmasq:

services:
  dnsmasq:
    image: pixelplastic/dnsmasq:local
    build: .
    restart: always
    networks:
      - dnsmasq
    cap_add:
      - 'NET_ADMIN'
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 67:67/udp
      - 68:68/udp
    environment:
      - TZ=Europe/Berlin
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './dnsmasq.conf:/etc/dnsmasq.conf:ro'
